### ISSUE TITLE
YouTube playlist support?

### ISSUE THREAD

**Issue by 9viz** [mlvzk/shovel-go#1]
It would make piko a lot more useful if YouTube playlist support is added.

Or am I missing something?

**Comment by mlvzk** [comment]
It does have playlist support, right now it's quite limited though, it only downloads the first 100 videos of the playlist, to get more I would probably have to use their API, which I don't want to do because of the quota limits.

**Comment by 9viz** [comment]
That's good enough for my needs. Also playlist support is not mentioned in README

**Comment by mlvzk** [comment]
I've updated the readme, thanks for your input!
https://github.com/mlvzk/piko/commit/fff3d76631ca479bbd3eacf0d62c8224fa77b2ca
